In [2]:
import torch
import random

In [6]:
random.sample(population=500, k=300)


TypeError: Population must be a sequence.  For dicts or sets, use sorted(d).

In [3]:
type(random.choices(population=[-10,20], k=30))

list

In [7]:
rotation_angles = [-30, -20, -10, 10, 20, 30]
to_generate_count = 3000
selected_angles = random.choices(population=rotation_angles, k=to_generate_count)

In [8]:
selected_angles

[20,
 -20,
 30,
 10,
 30,
 -10,
 10,
 -30,
 10,
 10,
 -20,
 -10,
 -30,
 10,
 10,
 20,
 -30,
 -10,
 -30,
 10,
 -10,
 -20,
 -10,
 -30,
 -20,
 30,
 20,
 -30,
 30,
 30,
 10,
 10,
 -20,
 -20,
 20,
 -30,
 -20,
 -30,
 -10,
 30,
 -10,
 10,
 -10,
 30,
 10,
 10,
 -30,
 30,
 20,
 -30,
 10,
 30,
 -10,
 30,
 10,
 30,
 10,
 10,
 20,
 -10,
 -20,
 20,
 10,
 30,
 10,
 -20,
 10,
 -10,
 -20,
 -30,
 20,
 -10,
 20,
 -20,
 -30,
 20,
 10,
 -20,
 -20,
 -30,
 -10,
 20,
 30,
 10,
 20,
 -30,
 -20,
 20,
 -10,
 20,
 -30,
 -20,
 20,
 -20,
 10,
 -20,
 10,
 20,
 10,
 -30,
 10,
 30,
 30,
 -30,
 -10,
 -30,
 10,
 -20,
 -20,
 -20,
 10,
 30,
 -20,
 20,
 -30,
 -20,
 -10,
 30,
 -30,
 -20,
 -10,
 20,
 10,
 -20,
 20,
 -30,
 -20,
 -20,
 -10,
 -10,
 -10,
 -10,
 -30,
 10,
 10,
 -30,
 20,
 20,
 -30,
 10,
 -20,
 -30,
 30,
 10,
 10,
 10,
 -30,
 30,
 30,
 30,
 -20,
 10,
 20,
 -30,
 -20,
 10,
 30,
 -20,
 10,
 -20,
 20,
 30,
 10,
 10,
 -10,
 30,
 30,
 -10,
 20,
 20,
 10,
 10,
 20,
 -30,
 10,
 20,
 20,
 -10,
 20,
 -20,
 30,
 -10,
 -30,

In [4]:
torch.randint( 0, 10, size=(30,), dtype=torch.long
    )

tensor([4, 4, 8, 2, 2, 8, 8, 8, 6, 6, 0, 4, 7, 2, 0, 7, 3, 0, 7, 8, 4, 8, 5, 4,
        2, 1, 2, 4, 2, 1])

In [2]:
torch.randint(-30, 31, size=(100,), dtype=torch.int32)

tensor([ 12,   9, -21,  -7,  12,  15,  26,  27,  15,  15, -24,  15,  26,  18,
        -23,  -8,  19,  13,   8,  27,   4,   0, -17,   9, -13,   9, -19,   3,
        -11,  11,  30,  12,  14,  27,  24,  27,  -7,   9,  21, -23,  25,   9,
        -24, -25,  30,   9,   2,  15,   4,  28, -21,  10,  30, -17, -12,  13,
        -15,  15, -20,  -9,   4,   1,   3,  25, -17,  30,  23,  30, -13,  19,
         24, -16,  27,  30,  24,  -6,  -9,  17,  -6, -28, -13, -16, -27,  30,
        -19, -15, -12,   3, -15, -15, -25,  -8,  12,  12, -23,  18, -10, -27,
        -15,  17], dtype=torch.int32)

In [3]:
torch.randint([-30, -20, 30], (10,))

TypeError: randint(): argument 'high' (position 1) must be int, not list

In [6]:
torch.randint(0, 40, size=(10,), dtype=torch.long)

tensor([ 3, 23, 15, 14, 16, 32, 19, 39, 31, 11])